### ISSUE TITLE
It looks the Khmer font was not embedded

### ISSUE THREAD

**Issue by Huyeng** [ODCambodia/Cambodia-ICTCamp#109]
Is it the Khmer font expected? 
<img width="1266" alt="screenshot at nov 09 22-40-16" src="https://user-images.githubusercontent.com/6613530/48272274-d113b580-e470-11e8-8d60-6ac33d7cfbd6.png">

**Comment by S-mardii** [comment]
Yes, it is.
Last time, @Punwath suggest using a more creative font style. Therefore, I worked with editor team to check for a new font on Google font, and we agreed to select this font for the website.
Do you have any comment?
