### ISSUE TITLE
[BUG] Order by alphabet of the title does not work very well

### ISSUE THREAD

**Issue by S-mardii** [ODCambodia/Cambodia-ICTCamp#137]
When order the facilitators by title, it appear that the order is not working very fine. 

I think it is the cause the added text of q Translate-x (`[:km]ចន្ទី[:en]Chanthy[:]`).

I think this can be solve by change the order by `title` to order by `slug`.

![image](https://user-images.githubusercontent.com/18528756/49220327-83072780-f408-11e8-820b-aab099de2e4d.png)

**Comment by S-mardii** [comment]
Bong @Huyeng, what is your advice.

**Comment by Huyeng** [comment]
It may cause by we use Khmer as the default site. Please update order by slug
