### ISSUE TITLE
Implement page "2018 Highlight"

### ISSUE THREAD

**Issue by S-mardii** [ODCambodia/Cambodia-ICTCamp#179]
The highlight page will display the slide presentations categorizing via thematic themes.

**Comment by S-mardii** [comment]
For now, we can use the highlight page as the resource page for 2018.

**Comment by Huyeng** [comment]
Request to show as list template
<img width="814" alt="screenshot at jan 31 00-47-24" src="https://user-images.githubusercontent.com/6613530/52001518-34eacf00-24f2-11e9-86dc-c3d73372ec7e.png">
