### ISSUE TITLE
Post Date Error in Khmer

### ISSUE THREAD

**Issue by S-mardii** [ODCambodia/Cambodia-ICTCamp#18]
When switching to the Khmer language, the date is wrongly displayed.

![image](https://user-images.githubusercontent.com/18528756/46076569-1e391200-c1b8-11e8-9856-18724b26318c.png)

**Comment by Huyeng** [comment]
Please use this function below to replace the cambodia_ict_camp_entry_footer();
```
<div class="posts-meta-div">
        <?php echo_ictcamp_post_meta(get_post(), array("date","categories","tags")); ?>
</div>

```
Replace:
```
<footer class="entry-footer">
    <?php cambodia_ict_camp_entry_footer(); ?>
</footer><!-- .entry-footer -->
```

**Comment by Huyeng** [comment]
I have created a file called utils-content.php to manage all additional functions for contents. I have removed the function from template-tag.php.
