### ISSUE TITLE
Homepage: the margins space of each session is not the same

### ISSUE THREAD

**Issue by Huyeng** [ODCambodia/Cambodia-ICTCamp#189]
Please make the space between each session to be consistent.

<img width="1018" alt="screenshot at feb 02 14-36-33" src="https://user-images.githubusercontent.com/6613530/52161481-f58dcf80-26f7-11e9-9d39-ee50fd9a0e3f.png">

**Comment by S-mardii** [comment]
Fixed in PR #190
