### ISSUE TITLE
The English font has not defined properly, it should be used consistently

### ISSUE THREAD

**Issue by Huyeng** [ODCambodia/Cambodia-ICTCamp#29]
See this!
<img width="1109" alt="screenshot at sep 30 16-24-10" src="https://user-images.githubusercontent.com/6613530/46255893-551b6a80-c4cd-11e8-8ec9-b12e73e75ee1.png">

**Comment by S-mardii** [comment]
I already defined this in style:
`body,
h1, 
h1 a, 
h2, 
h2 a, 
h3, 
h3 a, 
h4, 
h4 a, 
h5, 
h5 a, 
h6, 
h6 a, 
.main-navigation a, 
.slider-content 
.banner-title, 
.site-title, 
.site-title a, 
.feature-event 
span {
	font-family: Battambang;
}`

**Comment by S-mardii** [comment]
Fixed with #33
