### ISSUE TITLE
Translate Comment Sections

### ISSUE THREAD

**Issue by S-mardii** [ODCambodia/Cambodia-ICTCamp#70]
If all parts of the website are translated, the comment sections should be translated too

![image](https://user-images.githubusercontent.com/18528756/46848794-0a2b1c80-ce16-11e8-9690-5ab63c8566c8.png)

**Comment by Huyeng** [comment]
Check with the team first if the leave a comment should enable to not. If not, please keep to do later when you are  free.

**Comment by S-mardii** [comment]
Close as the comment section is not needed on the website.
