### ISSUE TITLE
Change `Speakers Page` to `Facilitator Page`

### ISSUE THREAD

**Issue by S-mardii** [ODCambodia/Cambodia-ICTCamp#76]
This morning, Bong Try preferred to convert Speaker page to Facilitator page.

The purpose of this change is to includes more sections as following:

1. Advisory Committee
2. Facilitators
3. Volunteers

**Comment by S-mardii** [comment]
Bong @Huyeng, to do this, I think we should:

- change `Speakers` custom post type to `Facilitator`
- create a new taxonomy for `Facilitator` to specify whether that person is a `Advisory Committee`, `Facilitators`, or `Volunteers`

**Comment by Huyeng** [comment]
Sounds good. Please go ahead.

**Comment by S-mardii** [comment]
Fixed by #77
